theme = "dracula"

[editor]
line-number = "relative"
mouse = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.insert]
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"C-p" = "move_line_up"
"C-n" = "move_line_down"